name: Toggle Demo Video Link

on:
  push:
    branches:
      - main

jobs:
  toggle-demo-video:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check current demo video link
        id: check-link
        run: |
          if grep -q 'spicfy1' README.md; then
            echo "spicfy1"
          else
            echo "spicfy"
          fi

      - name: Debug current link
        run: |
          current_link=$(echo "${{ steps.check-link.outputs.stdout }}")
          echo "Current link: $current_link"

      - name: Update Demo Video Link
        run: |
          current_link=$(echo "${{ steps.check-link.outputs.stdout }}")
          new_link=""
          if [ "$current_link" == "spicfy1" ]; then
            new_link="spicfy"
          else
            new_link="spicfy1"
          fi
          echo "Replacing $current_link with $new_link"
          sed -i "s|![Demo Video](https://github.com/Terminal127/nvim-spotify/blob/main/srcgif/$current_link.gif)|![Demo Video](https://github.com/Terminal127/nvim-spotify/blob/main/srcgif/$new_link.gif)|g" README.md

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git status
          git commit -m "Toggle demo video link [skip ci]"
          git push
